<Project Sdk="Microsoft.NET.Sdk.Razor">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>
	<ItemGroup>
	  <None Include="wwwroot\css\shared.css" />
	  <None Include="wwwroot\css\site.css" />
	</ItemGroup>
</Project>